### ISSUE TITLE
Design a dedicated page to allow user to finish the individual verification.

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-registrar#32]
Currently user clicks on the link (in Email, twitter CTA or Riot link) will implicitly finish the verification process. And user will be redirected back to *Litentry* website. This process is confusing for some user. Alternatively after user clicked on the respective link, additional page with the detail of the verification will be presented and user clicks on the CTA on that page to finish the verification process.

As of technical implementation, it's doable to introduce a small FE templating library to 
* render data in structured fashion.
* able to style things correctly.

**Comment by geastwood** [comment]
Templating engine such as [hogan.js](https://twitter.github.io/hogan.js/).

**Comment by geastwood** [comment]
![](https://docs.litentry.com/registrar/email.png)
Basically is to convert this email template into a page.

**Comment by chenzongxiong** [comment]
> Templating engine such as [hogan.js](https://twitter.github.io/hogan.js/).

I used template engine provided by https://lodash.com/docs/4.17.15#template to render email template

As for the static frontend pages, I think hogan.js would be a good choice
